### ISSUE TITLE
Need help with some HackerEarth questions.

### ISSUE THREAD

**Issue by AdityaSrivastava3107** [Bharathgopal/May2023#13]
1- https://www.hackerearth.com/practice/basic-programming/input-output/basics-of-input-output/practice-problems/algorithm/split-house-547be0e9/

2- https://www.hackerearth.com/practice/basic-programming/input-output/basics-of-input-output/practice-problems/algorithm/best-index-1-45a2f8ff/

3- https://www.hackerearth.com/practice/basic-programming/input-output/basics-of-input-output/practice-problems/algorithm/seven-segment-display-nov-easy-e7f87ce0/

I am not able to generate a proper logic for these three questions, can you please help me with it in our next webex session?

**Comment by logeshps02** [comment]
1. since they asked to print the one where most fences are placed, just fill all the empty spaces with fences ,so that the person can reach to his house only. we have to check if there is any consecutive houses present ,it is the only failing condition.

**Comment by AkrishtPrajapati** [comment]
Here is a approach for your first question .....

 
#include<stdio.h>
int main()
{
    int n,flag=0;
    scanf("%d",&n);
    char c[n];
    scanf("%s",c);
    for(int i=0;i<strlen(c);i++)
    {
        if(c[i]=='H'&&c[i+1]=='H')
        {
            flag=1;
        }
        else
        {
            if(c[i]=='.')
            c[i]='B';
        }
    }
    if(flag==1)
    {
    printf("NO\n");
    }
    else
{
    printf("YES\n");
    printf("%s",c);
}
}

Hope this will help you......

**Comment by KAVINMUTHU** [comment]
2. Logic for the Second Question:

so we have to calculate the special sum for a given index i  

---Start with the first element of the array, A[1], and add it to your sum.
---Move to the next two elements, A[i+1] and A[i+2], and add both of them to your sum.
---Continue this process, adding the next three elements each time, until you reach an index where it is no longer possible to pick three consecutive elements.

**Comment by logeshps02** [comment]
time limit exceeds in this approach ,is there any ways to solve that
