### ISSUE TITLE
Help in A Binary Palindrome.

### ISSUE THREAD

**Issue by dinesh494** [Bharathgopal/May2023#16]
**https://www.hackerearth.com/practice/basic-programming/recursion/recursion-and-backtracking/practice-problems/algorithm/binary-palindrome-4-035e5ad6/**

Sir, Please help in the code.

**Comment by Bharathgopal** [comment]
What is the exact help that you need?

**Comment by dinesh494** [comment]
Help in code 
it showing time exceed.

**Comment by npsnishant** [comment]
#include <stdio.h>
#include <stdlib.h>

// Function to check if a string is a palindrome
int isPalindrome(char* str, int len) {
    int left = 0, right = len - 1;
    while (left <= right) {
        if (str[left] != str[right])
            return 0;
        left++;
        right--;
    }
    return 1;
}

// Function to calculate the minimum number of operations
int minOperations(int N) {
    char binary[33];
    int len = 0;

    // Convert N to binary
    while (N > 0) {
        binary[len++] = (N % 2) + '0';
        N /= 2;
    }

    // Check if the binary representation is already a palindrome
    if (isPalindrome(binary, len))
        return 0;

    int left = 0, right = len - 1;
    int operations = 0;

    // Make the binary representation a palindrome
    while (left <= right) {
        if (binary[left] != binary[right])
            operations += abs(binary[left] - binary[right]);
        binary[right] = binary[left];
        left++;
        right--;
    }

    return operations;
}

int main() {
    int T;
    scanf("%d", &T);

    for (int i = 0; i < T; i++) {
        int N;
        scanf("%d", &N);
        int operations = minOperations(N);
        printf("%d\n", operations);
    }

    return 0;
}
Hope this will help....

**Comment by dinesh494** [comment]
It showing worng answer..

**Comment by Bharathgopal** [comment]
If you get time limit exceeding error, follow the below steps:

- Make sure your code is not stuck in loops
- Optimize the code by removing lengthy logic and unwanted logic
- Think of alternative logics which can use less instructions

**Comment by dinesh494** [comment]
Ok Sir.
