### ISSUE TITLE
#REGARDING MAIL

### ISSUE THREAD

**Issue by kabita-18** [Bharathgopal/May2023#18]
Not recieving mails regularly  . kindly solve my issue because tommorrow morning is deadline for quiz.

**Comment by AdityaSrivastava3107** [comment]
The quiz link is present on futureskills platform(Section 1) also.

**Comment by kabita-18** [comment]
My Futureskill platform is still not working.

**Comment by Bharathgopal** [comment]
Not relevant to the forum
