### ISSUE TITLE
Embedded Channel Login issue on Futureskill 

### ISSUE THREAD

**Issue by SanjanaTarlekar** [Bharathgopal/May2023#20]
I am not able to join Embedded channel it was showing access denied. Please can you allowed me to join the channel.
Mail id:- tarlekarsanjana@gmail.com
![Uploading IMG-20230527-WA0016.jpeg…]()

**Comment by Rahimunnis** [comment]
Dear sir/mam,
I am unable to find my channel (FY23 24 EmbeddedB1) in future skills platform and showing error while opening the content related to it. It showing that you dont have permission to access the card.l am unable to access c programming content .please do considered this issue.

Thanking you
Email id:rahimunny2001@gmail.com

**Comment by Bharathgopal** [comment]
Not relevant to the forum

**Comment by Rahimunnis** [comment]
I am enable to join in embedded channel .please allow me in to the channel, it showing access denied. Mail:rahimunny2001@gmail.com

**Comment by Bharathgopal** [comment]
@Rahimunnis , this forum is meant only for C Programming, Linux and Git related queries. 
Please use the forum responsibly without conflicts.
