### ISSUE TITLE
Online assessment link issue

### ISSUE THREAD

**Issue by AdityaSrivastava3107** [Bharathgopal/May2023#21]
Sir we haven't received any kind of information or mail regarding our online HackerEarth assessment that was scheduled for today(27th may). Some of the students did receive the mail and were able to to complete their assessment, what about the rest of us?

**Comment by Shafeeq-Ahmd** [comment]
same issue here, many of us didn't receive the email for the online HackerEarth assessment. humble request to address the issue.

**Comment by Bharathgopal** [comment]
Not relevant to the forum.
